# Site settings
email: hello@marcrey.es
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Blog
description: Data-driven developer and open source enthusiast.
url: "https://blog.marcrey.es"
twitter_username: marcreyesph
default_img: https://blog.marcrey.es/assets/images/og-image.png

# Profile settings
name: Marc Anthony Reyes
profile_img: /assets/images/about-small-colored.jpg
profile: Hi! My name is Marc and I'm a student developer from Cagayan de Oro, Philippines, and building interfaces and developing Machine Learning and AI applications for various causes are some of my skills as an up-and-coming developer. I'm also occasionally invited to speak at tech conferences to share my knowledge and experiences as a budding front end web developer-turned-data scientist.
social:
  github: https://github.com/marcreyesph
  medium: https://becominghuman.ai/@marcreyesph
  twitter: https://twitter.com/marcreyesph
  facebook: https://www.facebook.com/marcxplanet
  email: hello@marcrey.es


# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md", "vendor"]
markdown: kramdown
permalink: /blog/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
